### ISSUE TITLE
Обновление

### ISSUE THREAD

**Issue by fastumkruk** [zhuharev/qiwi#1]
Здравствуйте. Могли бы Вы обновить Ваш проект? Например функция последних платежей уже не работает. И например добавить функцию которая мониторит новый платеж?

**Comment by zhuharev** [comment]
Добрый день, постараюсь на выходных обновить. Пример функции мониторинга можете посмотреть в моей админке для киви-кошельков https://github.com/zhuharev/qiwi-admin/blob/master/pkg/syncronizer/syncronizer.go

**Comment by fastumkruk** [comment]
Здравствуйте. Обновите пожалуйста.

**Comment by zhuharev** [comment]
В общем я посмотрел, всё работает
